### PR TITLE
Bump cool.io dependency

### PR DESCRIPTION
**Pull request by sorah**

### CODE REVIEW

**Comment by kuenishi** [comment]
I can add you as a maintainer of this repo as msgpack-rpc organisation has very few activities, if you want and you're an active user of msgpack-rpc-ruby. Any thoughts, @suma ?

**Comment by suma** [comment]
I agree with kuenishi-san, I can add you to rubygems maintainer too.

**Comment by sorah** [comment]
I currently don't have strong motivation to maintain, but I can do my best :) my email address for rubygems.org is `her@sorah.jp`.

**Comment by suma** [comment]
@sorah Thank you, I added email to msgpack-rpc of rubygems.

**Comment by sorah** [comment]
@kuenishi let me have commit bit to this repository

**Comment by kuenishi** [comment]
I think invited @sorah . Please reach me out again if you're not invited or not permitted to merge this.

**Comment by sorah** [comment]
Still not having commit bit.

Looks like I don't have invitation to organization msgpack-rpc yet.

**Comment by kuenishi** [comment]
I retried. This time I'm sure because Github told me there was one pending invitation. Please check it out again.

**Comment by sorah** [comment]
worked!

**Pull request merged**
